# Generated by Django 3.0.6 on 2020-05-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberlist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
